import { WeatherData } from "../types";

export const mockWeatherData: WeatherData[] = [
  {
    city: "New York",
    temperature: { celsius: 22, fahrenheit: 72 },
    condition: "Clear Sky",
    conditionIcon: "🌞",
    humidity: 55,
    windSpeed: 10,
  },
  {
    city: "Los Angeles",
    temperature: { celsius: 25, fahrenheit: 77 },
    condition: "Sunny",
    conditionIcon: "🌞",
    humidity: 40,
    windSpeed: 12,
  },
  {
    city: "Chicago",
    temperature: { celsius: 15, fahrenheit: 59 },
    condition: "Partly Cloudy",
    conditionIcon: "⛅",
    humidity: 65,
    windSpeed: 8,
  },
  {
    city: "London",
    temperature: { celsius: 12, fahrenheit: 54 },
    condition: "Rainy",
    conditionIcon: "🌧️",
    humidity: 80,
    windSpeed: 15,
  },
  {
    city: "Tokyo",
    temperature: { celsius: 18, fahrenheit: 64 },
    condition: "Cloudy",
    conditionIcon: "☁️",
    humidity: 70,
    windSpeed: 5,
  },
  {
    city: "Sydney",
    temperature: { celsius: 30, fahrenheit: 86 },
    condition: "Hot",
    conditionIcon: "🔥",
    humidity: 40,
    windSpeed: 7,
  },
  {
    city: "Paris",
    temperature: { celsius: 20, fahrenheit: 68 },
    condition: "Clear Sky",
    conditionIcon: "🌞",
    humidity: 50,
    windSpeed: 10,
  },
  {
    city: "Berlin",
    temperature: { celsius: 10, fahrenheit: 50 },
    condition: "Overcast",
    conditionIcon: "☁️",
    humidity: 75,
    windSpeed: 18,
  },
  {
    city: "Moscow",
    temperature: { celsius: -5, fahrenheit: 23 },
    condition: "Snowy",
    conditionIcon: "❄️",
    humidity: 85,
    windSpeed: 20,
  },
  {
    city: "Dubai",
    temperature: { celsius: 35, fahrenheit: 95 },
    condition: "Hot",
    conditionIcon: "🔥",
    humidity: 30,
    windSpeed: 15,
  },
  {
    city: "Cape Town",
    temperature: { celsius: 18, fahrenheit: 64 },
    condition: "Partly Cloudy",
    conditionIcon: "⛅",
    humidity: 60,
    windSpeed: 25,
  },
  {
    city: "Toronto",
    temperature: { celsius: 5, fahrenheit: 41 },
    condition: "Snowy",
    conditionIcon: "❄️",
    humidity: 80,
    windSpeed: 12,
  },
  {
    city: "Rio de Janeiro",
    temperature: { celsius: 28, fahrenheit: 82 },
    condition: "Sunny",
    conditionIcon: "🌞",
    humidity: 65,
    windSpeed: 10,
  },
  {
    city: "Bangkok",
    temperature: { celsius: 32, fahrenheit: 90 },
    condition: "Hot",
    conditionIcon: "🔥",
    humidity: 80,
    windSpeed: 8,
  },
  {
    city: "Mumbai",
    temperature: { celsius: 27, fahrenheit: 81 },
    condition: "Humid",
    conditionIcon: "🌥️",
    humidity: 90,
    windSpeed: 14,
  },
  {
    city: "Rome",
    temperature: { celsius: 19, fahrenheit: 66 },
    condition: "Clear Sky",
    conditionIcon: "🌞",
    humidity: 55,
    windSpeed: 5,
  },
  {
    city: "Athens",
    temperature: { celsius: 22, fahrenheit: 72 },
    condition: "Sunny",
    conditionIcon: "🌞",
    humidity: 45,
    windSpeed: 18,
  },
  {
    city: "Barcelona",
    temperature: { celsius: 23, fahrenheit: 73 },
    condition: "Clear Sky",
    conditionIcon: "🌞",
    humidity: 40,
    windSpeed: 13,
  },
  {
    city: "Madrid",
    temperature: { celsius: 24, fahrenheit: 75 },
    condition: "Partly Cloudy",
    conditionIcon: "⛅",
    humidity: 50,
    windSpeed: 14,
  },
];
