import { WeatherData } from "../types";

export const mockWeatherData: WeatherData[] = [
  {
    city: "New York",
    temperatureCelsius: 22, 
    temperatureFahrenheit: 72, 
    condition: "Clear Sky",
    conditionIcon: "🌞", 
    humidity: 55, 
    windSpeed: 10, 
  },
  {
    city: "Los Angeles",
    temperatureCelsius: 25, 
    temperatureFahrenheit: 77, 
    condition: "Sunny",
    conditionIcon: "🌞", 
    humidity: 40, 
    windSpeed: 12, 
  },
  {
    city: "Chicago",
    temperatureCelsius: 15, 
    temperatureFahrenheit: 59,
    condition: "Partly Cloudy",
    conditionIcon: "⛅", 
    humidity: 65, 
    windSpeed: 8, 
  },
  {
    city: "London",
    temperatureCelsius: 12,
    temperatureFahrenheit: 54, 
    condition: "Rainy",
    conditionIcon: "🌧️", 
    humidity: 80, 
    windSpeed: 15, 
  },
  {
    city: "Tokyo",
    temperatureCelsius: 18, 
    temperatureFahrenheit: 64, 
    condition: "Cloudy",
    conditionIcon: "☁️", 
    humidity: 70, 
    windSpeed: 5,
  },
  {
    city: "Sydney",
    temperatureCelsius: 30,
    temperatureFahrenheit: 86,
    condition: "Hot",
    conditionIcon: "🔥", 
    humidity: 40, 
    windSpeed: 7, 
  },
  {
    city: "Paris",
    temperatureCelsius: 20, 
    temperatureFahrenheit: 68, 
    condition: "Clear Sky",
    conditionIcon: "🌞",
    humidity: 50, 
    windSpeed: 10, 
  },
  {
    city: "Berlin",
    temperatureCelsius: 10, 
    temperatureFahrenheit: 50, 
    condition: "Overcast",
    conditionIcon: "☁️",
    humidity: 75, 
    windSpeed: 18, 
  },
  {
    city: "Moscow",
    temperatureCelsius: -5,
    temperatureFahrenheit: 23, 
    condition: "Snowy",
    conditionIcon: "❄️",
    humidity: 85,
    windSpeed: 20,
  },
  {
    city: "Dubai",
    temperatureCelsius: 35, 
    temperatureFahrenheit: 95, 
    condition: "Hot",
    conditionIcon: "🔥", 
    humidity: 30, 
    windSpeed: 15, 
  },
  {
    city: "Cape Town",
    temperatureCelsius: 18, 
    temperatureFahrenheit: 64, 
    condition: "Partly Cloudy",
    conditionIcon: "⛅",
    humidity: 60, 
    windSpeed: 25, 
  },
  {
    city: "Toronto",
    temperatureCelsius: 5,
    temperatureFahrenheit: 41, 
    condition: "Snowy",
    conditionIcon: "❄️",
    humidity: 80,
    windSpeed: 12,
  },
  {
    city: "Rio de Janeiro",
    temperatureCelsius: 28,
    temperatureFahrenheit: 82,
    condition: "Sunny",
    conditionIcon: "🌞",
    humidity: 65,
    windSpeed: 10, 
  },
  {
    city: "Bangkok",
    temperatureCelsius: 32, 
    temperatureFahrenheit: 90,
    condition: "Hot",
    conditionIcon: "🔥", 
    humidity: 80, 
    windSpeed: 8,
  },
  {
    city: "Mumbai",
    temperatureCelsius: 27,
    temperatureFahrenheit: 81, 
    condition: "Humid",
    conditionIcon: "🌥️", 
    humidity: 90,
    windSpeed: 14, 
  },
  {
    city: "Rome",
    temperatureCelsius: 19, 
    temperatureFahrenheit: 66, 
    condition: "Clear Sky",
    conditionIcon: "🌞", 
    humidity: 55, 
    windSpeed: 5, 
  },
  {
    city: "Athens",
    temperatureCelsius: 22, 
    temperatureFahrenheit: 72, 
    condition: "Sunny",
    conditionIcon: "🌞", 
    humidity: 45, 
    windSpeed: 18, 
  },
  {
    city: "Barcelona",
    temperatureCelsius: 23, 
    temperatureFahrenheit: 73, 
    condition: "Clear Sky",
    conditionIcon: "🌞",
    humidity: 40,
    windSpeed: 13,
  },
  {
    city: "Madrid",
    temperatureCelsius: 24, 
    temperatureFahrenheit: 75, 
    condition: "Partly Cloudy",
    conditionIcon: "⛅", 
    humidity: 50,
    windSpeed: 14, 
  },
];

